/*

 BROTHEL_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Q:\PROJECTS\PERSONAL\GAMES\2021_06_HAGJ_GB\Resources\Town_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Brothel_Map_h_INCLUDE
#define __Brothel_Map_h_INCLUDE

#define Brothel_MapWidth 20
#define Brothel_MapHeight 18
#define Brothel_MapBank 0

extern const unsigned char Brothel_Map[];

#endif

/* End of BROTHEL_MAP.H */
