/*

 CAMP0_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Q:\PROJECTS\PERSONAL\GAMES\2021_06_HAGJ_GB\Resources\Town_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Camp0_Map_h_INCLUDE
#define __Camp0_Map_h_INCLUDE

#define Camp0_MapWidth 20
#define Camp0_MapHeight 18
#define Camp0_MapBank 0

extern const unsigned char Camp0_Map[];

#endif

/* End of CAMP0_MAP.H */
