/*

 CASTLE1_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Q:\PROJECTS\PERSONAL\GAMES\2021_06_HAGJ_GB\Resources\Castle_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Castle1_Map_h_INCLUDE
#define __Castle1_Map_h_INCLUDE

#define Castle1_MapWidth 20
#define Castle1_MapHeight 18
#define Castle1_MapBank 0

extern const unsigned char Castle1_Map[];

#endif

/* End of CASTLE1_MAP.H */
