/*

 TITLE_TEXTTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 14

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Title_TextTiles_h_INCLUDE
#define __Title_TextTiles_h_INCLUDE

/* Bank of tiles. */
#define Title_TextTilesBank 0
/* Start of tile array. */
extern const unsigned char Title_TextTiles[];

#endif

/* End of TITLE_TEXTTILES.H */
