/*

 TITLE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 20 x 48
   Tile set      : Q:\PROJECTS\PERSONAL\GAMES\2021_06_HAGJ_GB\Resources\Title.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Title_Map_h_INCLUDE
#define __Title_Map_h_INCLUDE

#define Title_MapWidth 20
#define Title_MapHeight 48
#define Title_MapBank 3

extern const unsigned char Title_Map[];

#endif

/* End of TITLE_MAP.H */
