/*

 WINDOWS_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 46

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Windows_Tiles_h_INCLUDE
#define __Windows_Tiles_h_INCLUDE

/* Bank of tiles. */
#define Windows_TilesBank 0
/* Start of tile array. */
extern const unsigned char Windows_Tiles[];

#endif

/* End of WINDOWS_TILES.H */
