/*

 WINDOWS_TEXT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 160
   Tile set      : Q:\PROJECTS\PERSONAL\GAMES\2021_06_HAGJ_GB\Resources\Windows_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Windows_Text_h_INCLUDE
#define __Windows_Text_h_INCLUDE

#define Windows_TextWidth 20
#define Windows_TextHeight 160
#define Windows_TextBank 0

extern const unsigned char Windows_Text[];

#endif

/* End of WINDOWS_TEXT.H */
