/*

 WORLD_MAP_BRITAIN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 130 x 233
   Tile set      : Q:\PROJECTS\PERSONAL\GAMES\2021_06_HAGJ_GB\Resources\World_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __World_Map_Britain_h_INCLUDE
#define __World_Map_Britain_h_INCLUDE

#define World_Map_BritainWidth 130
#define World_Map_BritainHeight 233
#define World_Map_BritainBank 1

extern const unsigned char World_Map_Britain[];

#endif

/* End of WORLD_MAP_BRITAIN.H */
