/*

 WORLD_MAP_SMALL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Q:\PROJECTS\PERSONAL\GAMES\2021_06_HAGJ_GB\Resources\World_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __World_Map_Small_h_INCLUDE
#define __World_Map_Small_h_INCLUDE

#define World_Map_SmallWidth 20
#define World_Map_SmallHeight 18
#define World_Map_SmallBank 0

extern const unsigned char World_Map_Small[];

#endif

/* End of WORLD_MAP_SMALL.H */
