/*

 WORLD_MAP_IRELAND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 2
   Map size      : 100 x 120
   Tile set      : Q:\PROJECTS\PERSONAL\GAMES\2021_06_HAGJ_GB\Resources\World_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __World_Map_Ireland_h_INCLUDE
#define __World_Map_Ireland_h_INCLUDE

#define World_Map_IrelandWidth 100
#define World_Map_IrelandHeight 120
#define World_Map_IrelandBank 2

extern const unsigned char World_Map_Ireland[];

#endif

/* End of WORLD_MAP_IRELAND.H */
